version: '3.5'

services:
  scrypted:
    image: koush/scrypted
    container_name: scrypted
    restart: unless-stopped
    volumes:
      - ~/.scrypted/volume:/server/volume
    ports:
      - "10443:10443"
    env_file: .env.scrypted
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "10"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env.nginx
    volumes:
      - ./nginx:/etc/nginx
      - ~/.certbot/conf:/etc/letsencrypt
      - ~/.certbot/www:/var/www/certbot
    tmpfs:
      - /etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "10"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ~/.certbot/conf:/etc/letsencrypt
      - ~/.certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: "/bin/sh -c 'trap exit TERM; apk update && apk add --no-cache docker-cli; while :; do certbot renew; docker exec nginx nginx -s reload; sleep 12h & wait $${!}; done;'"

  web:
    image: scrypted-sidecar/web
    container_name: web
    restart: unless-stopped
    environment:
      PORT: 3000
      BACKEND_URL: http://server:5000
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "10"

  server:
    image: scrypted-sidecar/server
    container_name: server
    restart: unless-stopped
    env_file: .env.server
    environment:
      PORT: 5000
      SCRYPTED_HOST: scrypted
      SCRYPTED_PORT: 10443
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "10"
    volumes:
      - ~/.sidecar/volume:/server/volume
